In [1]:
from numpy import *
 
a = array([[0,1,1,0],
           [1,0,0,1],
           [1,0,0,1],
           [1,1,0,0]],dtype = float)  #dtype指定为float

In [2]:
print(a)

[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 0. 0.]]


In [5]:
b = transpose(a)  #b为a的转置矩阵

In [6]:
print(b)

[[0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]]


In [12]:
c = zeros((a.shape),dtype = float)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c[i][j] = a[i][j] / (b[j].sum())  #完成初始化分配

In [13]:
print(c)

[[0.         0.5        1.         0.        ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.         0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]


In [16]:
pr = zeros((c.shape[0],1),dtype = float)  #构造一个存放pr值得矩阵
for i in range(c.shape[0]):
    pr[i] = float(1)/c.shape[0]

In [19]:
p = 0.8   

In [21]:
D= p*dot(c,pr) + (1-p)*pr
        #print (v == p*dot(m,v) + (1-p)*v).all()

In [22]:
D

array([[0.35      ],
       [0.21666667],
       [0.21666667],
       [0.21666667]])

In [ ]:
print pageRank(p,M,pr)  # 计算pr值  